triggers:
  - Modality: CT
    SeriesDescription: "[*]"
  - Modality: MR

flows:
  - container_tag: hello-world
    input_path: /input
    output_path: /output
    gpu: False
  - container_tag: hello-world
    input_path: /input
    output_path: /output
    gpu: True
  - container_tag: hello-world
    input_path: /input
    output_path: /output
    gpu: False

destinations:
  - hostname: localhost
    port: 10000
    ae_title: STORESCP
  - hostname: localhost1
    port: 10001
    ae_title: STORESCP1