# RabbitMQ
RABBIT_HOSTNAME: "rabbit"
RABBIT_PORT: 5672

# Logging
LOG_NAME: "SCHEDULER"
LOG_DIR: "/opt/DicomFlow/logs"
LOG_LEVEL: 20
LOG_FORMAT: "%(levelname)s ; %(asctime)s ; %(name)s ; %(filename)s ; %(funcName)s ; %(lineno)s ; %(message)s"
LOG_PUB_MODELS:
  - exchange: logs

SUB_QUEUE_KWARGS:
  queue: ""
  passive: False
  durable: False
  exclusive: False
  auto_delete: True
SUB_PREFETCH_COUNT: 1
SUB_CONSUMER_EXCHANGE: &SUB_CONSUMER_EXCHANGE "consumer"
SUB_RESCHEDULE_PRIORITY: 5
SUB_MODELS:
  - exchange: "fingerprinter"
    exchange_type: "topic"
    routing_keys: ["success"]
    routing_key_fetch_echo: "fetch"
  - exchange: *SUB_CONSUMER_EXCHANGE
    exchange_type: "topic"
    routing_keys: ["success", "error", "fail"]
    routing_key_fetch_echo: "fetch"


PUB_ROUTING_KEY_ERROR: "error"
PUB_ROUTING_KEY_SUCCESS: "success"
PUB_ROUTING_KEY_FAIL: "fail"
PUB_ROUTING_KEY_GPU: "GPU"
PUB_ROUTING_KEY_CPU: "CPU"

PUB_MODELS:
  - exchange: "scheduler"
    exchange_type: "topic"
