# RabbitMQ
RABBIT_HOSTNAME: "localhost"
RABBIT_PORT: 5672
RABBIT_USERNAME: "guest"
RABBIT_PASSWORD: "guest"

# Logging
LOG_NAME: "FINGERPRINTER"
LOG_DIR: "/opt/DicomFlow/logs"
LOG_LEVEL: 20
LOG_FORMAT: "%(levelname)s ; %(asctime)s ; %(name)s ; %(filename)s ; %(funcName)s ; %(lineno)s ; %(message)s"

# FINGERPRINTER
FLOW_DIRECTORY: "/opt/DicomFlow/flows"

SUB_ROUTING_KEY: "STORESCP_FINISHED"
SUB_EXCHANGE: ""
SUB_ROUTING_KEY_AS_QUEUE: True
SUB_EXCHANGE_TYPE: "direct"
SUB_PREFETCH_COUNT: 1

PUB_ROUTING_KEY: "FINGERPRINTER_FINISHED"
PUB_EXCHANGE: ""
PUB_ROUTING_KEY_AS_QUEUE: True
PUB_EXCHANGE_TYPE: "direct"

