# RabbitMQ
RABBIT_HOSTNAME: "rabbit"
RABBIT_PORT: 5672

# Logging
LOG_NAME: "JANITOR"
LOG_DIR: "/opt/DicomFlow/logs"
LOG_LEVEL: 20
LOG_FORMAT: "%(levelname)s ; %(asctime)s ; %(name)s ; %(filename)s ; %(funcName)s ; %(lineno)s ; %(message)s"
LOG_PUB_MODELS:
  - exchange: logs

# File Storage
FILE_STORAGE_URL: "http://file-storage:2244"

# Janitor
DATABASE_PATH: "/opt/DicomFlow/database/database.sqlite"

FILE_DELETE_RULES:
  - on_exchange: "storescu"
    on_routing_key: "#"
    delete_input_file: True
    delete_output_file: True
    event_kwargs:
      id: id
  - on_exchange: "fingerprinter"
    on_routing_key: "#"
    delete_input_file: True
    delete_output_file: False
    event_kwargs:
      uid: uid
      exchange: storescp

  - on_exchange: "#"
    on_routing_key: "fail"
    delete_input_file: True
    delete_output_file: True
    event_kwargs:
      id: id

# MQSub
PUB_ROUTING_KEY_ERROR: "error"
SUB_QUEUE_KWARGS:
    queue: ""
    passive: False
    durable: False
    exclusive: False
    auto_delete: True
SUB_PREFETCH_COUNT: 10
SUB_MODELS:
  - exchange: "storescp"
    exchange_type: "topic"
    routing_key: "#"
  - exchange: "fingerprinter"
    exchange_type: "topic"
    routing_key: "success"
  - exchange: "storescu"
    exchange_type: "topic"
    routing_key: "#"
