# RabbitMQ
RABBIT_HOSTNAME: "localhost"
RABBIT_PORT: 5672

# Logging
LOG_NAME: "STORESCP"
LOG_DIR: "/opt/DicomFlow/logs"
LOG_LEVEL: 20
LOG_FORMAT: "%(levelname)s ; %(asctime)s ; %(name)s ; %(filename)s ; %(funcName)s ; %(lineno)s ; %(message)s"
LOG_PUB_MODELS:
  - exchange: logs

# File Storage
FILE_STORAGE_URL: "http://localhost:2244"

# SCP
AE_TITLE: "STORESCP"
AE_HOSTNAME: "localhost"
AE_PORT: 10000
PYNETDICOM_LOG_LEVEL: "standard"
TAR_SUBDIR: []
PUB_MODELS:
  - exchange: "storescp"
    exchange_type: "topic"
    routing_key_success: "success"
    routing_key_fail: "fail"

