name: CI DicomFlow

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

        
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push base
        uses: docker/build-push-action@v5
        with:
          context: ./base
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dicom_flow-base:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/dicom_flow-base:${{ steps.date.outputs.date }}

      - name: Build and push STORESCP
        uses: docker/build-push-action@v5
        with:
          context: ./storescp
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dicom_flow-storescp:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/dicom_flow-storescp:${{ steps.date.outputs.date }}

      - name: Build and push Fingerprinter
        uses: docker/build-push-action@v5
        with:
          context: ./fingerprinter
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dicom_flow-fingerprinter:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/dicom_flow-fingerprinter:${{ steps.date.outputs.date }}

      - name: Build and push Scheduler
        uses: docker/build-push-action@v5
        with:
          context: ./scheduler
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dicom_flow-scheduler:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/dicom_flow-scheduler:$NOW

      - name: Build and push File_Storage
        uses: docker/build-push-action@v5
        with:
          context: ./file_storage
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dicom_flow-file_storage:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/dicom_flow-file_storage:${{ steps.date.outputs.date }}
     

      - name: Build and push STORESCU
        uses: docker/build-push-action@v5
        with:
          context: ./storescu
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dicom_flow-storescu:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/dicom_flow-storescu:${{ steps.date.outputs.date }}
      
      - name: Build and push Consumer
        uses: docker/build-push-action@v5
        with:
          context: ./consumer
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dicom_flow-consumer:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/dicom_flow-consumer:${{ steps.date.outputs.date }}
      
      - name: Build and push FlowTracker
        uses: docker/build-push-action@v5
        with:
          context: ./flow_tracker
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dicom_flow-flow_tracker:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/dicom_flow-flow_tracker:${{ steps.date.outputs.date }}
